name: Makefile CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-22.04

    steps:
    - uses: actions/checkout@v3

    - name: Install dependencies
      run: make

  uint-test:
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v3
    - name: Run Unit Test
      run: |
        make unit-test

